spring:
  cloud:
    gateway:
      routes:
        - id: church-lite-backend
          uri: http://localhost:5050
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}

        - id: smart-report-backend
          uri: http://localhost:5070
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}

        - id: sitemercado-backend
          uri: https://service.sitemercado.com.br
          predicates:
            - Path=/sitemercado/**
          filters:
            - RewritePath=/sitemercado/(?<segment>.*), /api/v1/${segment}
            - RemoveRequestHeader=X-Forwarded-For
            - RemoveRequestHeader=Via
            - RemoveRequestHeader=Forwarded
            - RemoveRequestHeader=X-Real-IP
            - AddRequestHeader=X-Forwarded-For, 0.0.0.0

  application:
    name: api-gateway

server:
  port: 5000

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    org.springframework.cloud.gateway: DEBUG