spring:
  cloud:
    gateway:
      routes:
        - id: church-lite-backend
          uri: http://localhost:5050
          predicates:
            - Path=/api/church-lite/**
          filters:
            - RewritePath=/api/church-lite/(?<segment>.*), /${segment}

        - id: smart-report-backend
          uri: http://localhost:5070
          predicates:
            - Path=/api/smartreport/**
          filters:
            - RewritePath=/api/smartreport/(?<segment>.*), /${segment}

  application:
    name: api-gateway

server:
  port: 5000

logging:
  level:
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    org.springframework.cloud.gateway: DEBUG