spring:
  cloud:
    gateway:
      routes:
        - id: church-lite-backend
          uri: http://localhost:5050
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*), /${segment}

  application:
    name: api-gateway

server:
  port: 5000