spring:
  cloud:
    gateway:
      routes:
        - id: front-end-route
          uri: http://localhost:3000
          predicates:
            - Path=/app/**
          filters:
            - RewritePath=/app/(?<segment>.*), /${segment}
  application:
    name: api-gateway

server:
  port: 7000